SET SCHEMA fn45297;

--Create triggers

CREATE TRIGGER CHECK_STROCK
AFTER INSERT ON PURCHASE
REFERENCING NEW ROW AS NEWROW
FOR EACH ROW 
WHEN ('Y' <>  (SELECT stock FROM product WHERE idProduct = NEWROW.idProduct))
DELETE FROM PURCHASE WHERE idPurchase = NEWROW.idPurchase;

--TEST
UPDATE PRODUCT SET stock = 'N' WHERE idProduct =1;
INSERT INTO Purchase(idClient,idEmployee,idProduct,amount)
   VALUES (1,2,1,1);
   
--
CREATE TRIGGER SET_VAT
BEFORE INSERT ON PRODUCT
REFERENCING NEW ROW AS NEWROW
FOR EACH ROW
WHEN ( NEWROW.VAT IS NULL)
SET VAT = (PRICE*20)/100;

--TEST
INSERT INTO Product (idProduct, name, price)
  VALUES (0009, 'Pot', 4.00);

CREATE TRIGGER REFLECT_DELIVERY
AFTER INSERT ON SUPPLIES
REFERENCING NEW ROW AS NEWROW
FOR EACH ROW 
UPDATE PRODUCT SET stock = 'Y' WHERE idProduct = NEWROW.idProduct;

CREATE TRIGGER SET_GTOTAL
BEFORE INSERT ON PURCHASE
REFERENCING NEW ROW AS NEWROW
FOR EACH ROW 
WHEN (NEWROW.gTotal is NULL )
SET gTotal = (SELECT price FROM PRODUCT WHERE idProduct = NEWROW.idProduct);

CREATE TRIGGER SET_NTOTAL
BEFORE INSERT ON PURCHASE
REFERENCING NEW ROW AS NEWROW
FOR EACH ROW 
WHEN (NEWROW.NTotal is NULL )
SET nTotal = (SELECT price FROM PRODUCT WHERE idProduct = NEWROW.idProduct) - 
			(SELECT VAT FROM PRODUCT WHERE idProduct = NEWROW.idProduct);

