SET SCHEMA fn45297;

CREATE VIEW GET_GARDEN_PRODUCT
AS SELECT *
FROM Product JOIN GARDEN
ON Product.idProduct = GARDEN.idGarden;

CREATE VIEW GET_PURCHASE
AS SELECT * FROM PURCHASE;

INSERT INTO GET_PURCHASE
VALUES ('Lego', 2016, 100, 'Y', 'MGM', 199);